[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Mx437 IBM VGA 8x16"
FontSize="14"

KeyboardSize="0.4"
RoundCorners="0"

HourFormat="HH:mm"
DateFormat="dddd, d MMMM"

HeaderText=""

#################### Background ####################

Background="Assets/background.png"
DimBackground="0.2"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#D27389"
DateTextColor="#6a7a8a"
TimeTextColor="#D27389"

FormBackgroundColor="#000000"
BackgroundColor="#000000"
DimBackgroundColor="#000000"

LoginFieldBackgroundColor="transparent"
PasswordFieldBackgroundColor="transparent"
LoginFieldTextColor="#cdd3e0"
PasswordFieldTextColor="#cdd3e0"
UserIconColor="#6a7a8a"
PasswordIconColor="#6a7a8a"

PlaceholderTextColor="#6a7a8a"
WarningColor="#BB607B"

LoginButtonTextColor="#000000"
LoginButtonBackgroundColor="#D27389"
SystemButtonsIconsColor="#6a7a8a"
SessionButtonTextColor="#6a7a8a"
VirtualKeyboardButtonTextColor="#6a7a8a"

DropdownTextColor="#cdd3e0"
DropdownSelectedBackgroundColor="#6a7a8a"
DropdownBackgroundColor="#000000"

HighlightTextColor="#000000"
HighlightBackgroundColor="#D27389"
HighlightBorderColor="transparent"

HoverUserIconColor="#cdd3e0"
HoverPasswordIconColor="#cdd3e0"
HoverSystemButtonsIconsColor="#cdd3e0"
HoverSessionButtonTextColor="#ffffff"
HoverVirtualKeyboardButtonTextColor="#ffffff"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="12"
Blur="2.0"

HaveFormBackground="true"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
